version: '3.3'

services:
  traefik:
    image: traefik
    command: 
      - --DEBUG
      - --docker.watch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443

  dstu3:
    build:
      context: ./dstu3/
    ports:
      - "8080"
    labels:
      traefik.frontend.rule: "PathPrefix:/dstu3"

  dstu2:
    build:
      context: ./dstu2/
    ports:
      - "8081"
    labels:
      traefik.frontend.rule: "PathPrefix:/dstu2"