version: '3.3'

services:
  traefik:
    image: traefik
    command: 
      - --DEBUG
      - --docker.watch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443

  # dstu3:
  #   build:
  #     context: ./dstu3/
  #   labels:
  #     traefik.frontend.rule: "PathPrefix:/cqf-ruler/baseDstu3"

  dstu2:
    build:
      context: ./dstu2/
    labels:
      traefik.frontend.rule: "PathPrefix:/cqf-ruler/baseDstu2"

  # dstu4:
  #   build:
  #     context: ./r4/
  #   labels:
  #     traefik.frontend.rule: "PathPrefix:/cqf-ruler/baseR4"

#  cdshooks:
#    build:
#      context: ./cdshooks/
#    depends_on:
#      - dstu3
#    labels:
#      traefik.frontend.rule: "PathPrefix:/cqf-ruler/cds-services"